[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "IHP-open-IP"
authors = [{name = "IHP PDK Authors", email = "openpdk@ihp-microelectronics.com"}]
dynamic = ["version", "description"]
