v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
N -220 -110 -220 -80 {
lab=pt_s}
N -220 -110 -0 -110 {
lab=pt_s}
N -0 -110 -0 -60 {
lab=pt_s}
N 0 60 0 90 {
lab=pt_d}
N -120 0 -120 20 {
lab=pt_g}
N -120 0 -60 0 {
lab=pt_g}
N -220 -20 -220 180 {
lab=GND}
N -120 180 0 180 {
lab=GND}
N 0 150 -0 180 {
lab=GND}
N -120 80 -120 180 {
lab=GND}
N -220 180 -120 180 {
lab=GND}
N -120 180 -120 220 {
lab=GND}
C {/home/ac3e/Documents/ihp_design/xschem/pass_transistor.sym} 0 0 0 0 {name=x1}
C {devices/code_shown.sym} -350 -610 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file \{filename\}_\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the power supply rejection ratio of the amplifier

*.include \{DUT_path\}

.lib \{PDK_ROOT\}/\{PDK\}/libs.tech/ngspice/models/cornerMOSlv.lib \{corner\}

.option TEMP=\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {devices/code_shown.sym} -340 -350 0 0 {name=CONTROL only_toplevel=false value=".control
pre_osdi /home/ac3e/Documents/psp103_nqs.osdi
op
*set wr_singlescale
*wrdata \{simpath\}/\{filename\}_\{N\}.data -I(Vvdd)
let current = (v(pt_s)-v(pt_g))/1000
print current
wrdata \{simpath\}/\{filename\}_\{N\}.data current
quit
.endc
"}
C {devices/vsource.sym} -220 -50 0 0 {name=V1 value=1.8 savecurrent=false}
C {devices/vsource.sym} 0 120 0 0 {name=V3 value=1.2 savecurrent=false}
C {devices/vsource.sym} -120 50 0 0 {name=V2 value=1 savecurrent=false}
C {devices/gnd.sym} -120 220 0 0 {name=l1 lab=GND}
C {devices/lab_pin.sym} 0 -90 0 0 {name=p1 sig_type=std_logic lab=pt_s}
C {devices/lab_pin.sym} -120 0 0 0 {name=p2 sig_type=std_logic lab=pt_g}
C {devices/lab_pin.sym} 0 70 0 0 {name=p3 sig_type=std_logic lab=pt_d}
